version: '3.2'

services:
  minio:
    image: 'minio/minio:latest'
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'minio'
      MINIO_ROOT_PASSWORD: 'minio123'
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      - film
    volumes:
      - minio_film:/data

  create_s3_buckets:
    image: minio/mc
    environment:
      MINIO_ROOT_USER: 'minio'
      MINIO_ROOT_PASSWORD: 'minio123'
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " until (/usr/bin/mc config host add minio http://minio:9000 minio minio123) do echo '...waiting...' && sleep 10; done; /usr/bin/mc mb minio/film; /usr/bin/mc anonymous set public minio/film; tail -f /dev/null;"
    networks:
      - film

volumes:
  minio_film: { }

networks:
  film:
    driver: bridge